import unittest
# from climate_scanner.trends_innovation_classifier.data_utils import format_outputData
from data_utils import format_outputData

class TestFormatOutputData(unittest.TestCase):

    def test_format_outputData(self):
        outputData = [{'id': 2,
                   'title': 'Artificial Intelligence Explained in Simple Terms',
                   'prev_id': [],
                   'prev_pos': [],
                   'prev_text': '',
                   'curr_id': 0,
                   'curr_pos': (0, 114),
                   'curr_text': 'Artificial Intelligence (AI) involves using computers to do things that traditionally require human intelligence .',
                   'next_id': 1,
                   'next_pos': (115, 199),
                   'next_text': 'This means creating algorithms to classify, analyze, and draw predictions from data.',
                   'category': 'Artificial Intelligence',
                   'climate_scanner': True},
                  {'id': 2,
                   'title': 'Artificial Intelligence Explained in Simple Terms',
                   'prev_id': 0,
                   'prev_pos': (0, 114),
                   'prev_text': 'Artificial Intelligence (AI) involves using computers to do things that traditionally require human intelligence .',
                   'curr_id': 1,
                   'curr_pos': (115, 199),
                   'curr_text': 'This means creating algorithms to classify, analyze, and draw predictions from data.',
                   'next_id': 2,
                   'next_pos': (200, 281),
                   'next_text': 'It also involves acting on data, learning from new data, and improving over time.',
                   'category': 'Artificial Intelligence',
                   'climate_scanner': True},
                  {'id': 2,
                   'title': 'Artificial Intelligence Explained in Simple Terms',
                   'prev_id': 1,
                   'prev_pos': (115, 199),
                   'prev_text': 'This means creating algorithms to classify, analyze, and draw predictions from data.',
                   'curr_id': 2,
                   'curr_pos': (200, 281),
                   'curr_text': 'It also involves acting on data, learning from new data, and improving over time.',
                   'next_id': [],
                   'next_pos': [],
                   'next_text': '',
                   'category': 'Artificial Intelligence',
                   'climate_scanner': True},
                  {'id': 4,
                   'title': 'What is AI technology and how is it used?',
                   'prev_id': [],
                   'prev_pos': [],
                   'prev_text': '',
                   'curr_id': 0,
                   'curr_pos': (0, 88),
                   'curr_text': 'Artificial intelligence or AI is a popular buzzword you’ve probably heard or read about.',
                   'next_id': 1,
                   'next_pos': (89, 196),
                   'next_text': 'Articles about robots, technology, and the digital age may fill your head when you think about the term AI.',
                   'category': 'Artificial Intelligence',
                   'climate_scanner': True},
                  {'id': 4,
                   'title': 'What is AI technology and how is it used?',
                   'prev_id': 0,
                   'prev_pos': (0, 88),
                   'prev_text': 'Artificial intelligence or AI is a popular buzzword you’ve probably heard or read about.',
                   'curr_id': 1,
                   'curr_pos': (89, 196),
                   'curr_text': 'Articles about robots, technology, and the digital age may fill your head when you think about the term AI.',
                   'next_id': 2,
                   'next_pos': (197, 239),
                   'next_text': 'But what is it really, and how is it used?',
                   'category': 'Artificial Intelligence',
                   'climate_scanner': True}]
        result = format_outputData(outputData)
        output = [{'meta': {'doc_id': 2, 'sent_id': 0, 'sent_start_pos': [], 'sent_end_pos': 199, 'title': 'Artificial Intelligence Explained in Simple Terms'},
                   'text': ' Artificial Intelligence (AI) involves using computers to do things that traditionally require human intelligence . This means creating algorithms to classify, analyze, and draw predictions from data.'},
                  {'meta': {'doc_id': 2, 'sent_id': 1, 'sent_start_pos': 0, 'sent_end_pos': 281, 'title': 'Artificial Intelligence Explained in Simple Terms'},
                   'text': 'Artificial Intelligence (AI) involves using computers to do things that traditionally require human intelligence . This means creating algorithms to classify, analyze, and draw predictions from data. It also involves acting on data, learning from new data, and improving over time.'},
                  {'meta': {'doc_id': 2, 'sent_id': 2, 'sent_start_pos': 115, 'sent_end_pos': [], 'title': 'Artificial Intelligence Explained in Simple Terms'},
                   'text': 'This means creating algorithms to classify, analyze, and draw predictions from data. It also involves acting on data, learning from new data, and improving over time. '},
                  {'meta': {'doc_id': 4, 'sent_id': 0, 'sent_start_pos': [], 'sent_end_pos': 196, 'title': 'What is AI technology and how is it used?'},
                   'text': ' Artificial intelligence or AI is a popular buzzword you’ve probably heard or read about. Articles about robots, technology, and the digital age may fill your head when you think about the term AI.'},
                  {'meta': {'doc_id': 4, 'sent_id': 1, 'sent_start_pos': 0, 'sent_end_pos': 239, 'title': 'What is AI technology and how is it used?'},
                   'text': 'Artificial intelligence or AI is a popular buzzword you’ve probably heard or read about. Articles about robots, technology, and the digital age may fill your head when you think about the term AI. But what is it really, and how is it used?'}]
        self.assertEqual(result, output, "Valid Prodigy Format")


if __name__ == '__main__':
    unittest.main()